//@version=5
indicator(shorttitle="BB", title="Bollinger Bands", overlay=true, timeframe="", timeframe_gaps=true)
length = input.int(20, minval=1)
src = input(close, title="Source")
mult = input.float(2.0, minval=0.001, maxval=50, title="StdDev")
basis = ta.sma(src, length)
dev = mult * ta.stdev(src, length)
upper = basis + dev
lower = basis - dev
offset = input.int(10, "Offset", minval = -500, maxval = 500)
near_offset = input.int(20, "Near Offset")
// plot(basis, "Basis", color=#FF6D00, offset = offset)
// p1 = plot(upper, "Upper", color=#2962FF, offset = offset)
// p1 = plot(lower, "Lower", color=#2962FF, offset = offset)
// fill(p1, p2, title = "Background", color=color.rgb(33, 150, 243, 95))

between(price, min,max) =>
    is_between = price <= max and price >= min
    is_between

isPriceNearLower(lower, price) =>
    max = lower + near_offset
    min = lower - near_offset
    is_below = between(price, min, max)
    is_below

//plotshape(ta.crossunder(low, lower), title= "BB down", style=shape.triangledown, color=color.white, location=location.abovebar)
plotshape(isPriceNearLower(lower, low), title= "BB down", style=shape.square, color=color.white, location=location.belowbar)

