//@version=4
study(shorttitle="BB", title="Bollinger Bands", overlay=true)
length = input(title="Length", type=input.integer, defval=20, minval=1)
src = input(close, title="Source")
mult = input(type=input.float, defval=2.0, minval=0.001, maxval=50, title="StdDev")
offset = input(defval=10, title="Offset", type=input.integer, minval = -500, maxval = 500)
near_offset = input(defval=20, title="Near Offset", type=input.integer)

basis = sma(src, length)
dev = mult * stdev(src, length)
upper = basis + dev
lower = basis - dev
// plot(basis, "Basis", color=#FF6D00, offset = offset)
// p1 = plot(upper, "Upper", color=#2962FF, offset = offset)
// p1 = plot(lower, "Lower", color=#2962FF, offset = offset)
// fill(p1, p2, title = "Background", color=color.rgb(33, 150, 243, 95))

between(price, min,max) =>
    is_between = price <= max and price >= min
    is_between

isPriceNearLower(lower, price) =>
    max = lower + near_offset
    min = lower - near_offset
    is_near = between(price, min, max)
    is_near

isPriceNearUpper(upper, price) =>
    max = upper + near_offset
    min = upper - near_offset
    is_near = between(price, min, max)
    is_near

price_near_lower_bb = isPriceNearLower(lower, low)
price_near_upper_bb = isPriceNearUpper(upper, high)

//plotshape(ta.crossunder(low, lower), title= "BB down", style=shape.triangledown, color=color.white, location=location.abovebar)
plotshape(price_near_low_bb, title= "BB down", style=shape.square, color=color.white, location=location.belowbar)

